USE [master]
GO

/****** Object:  Database [ProjectMgmt]    Script Date: 05-03-2020 16:41:35 ******/
CREATE DATABASE [ProjectMgmt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectMgmt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectMgmt.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjectMgmt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ProjectMgmt_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjectMgmt] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectMgmt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectMgmt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectMgmt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectMgmt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectMgmt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectMgmt] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectMgmt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectMgmt] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectMgmt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectMgmt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectMgmt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectMgmt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectMgmt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectMgmt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectMgmt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectMgmt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectMgmt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectMgmt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectMgmt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectMgmt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectMgmt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectMgmt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectMgmt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectMgmt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectMgmt] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectMgmt] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectMgmt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectMgmt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectMgmt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectMgmt] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjectMgmt] SET  READ_WRITE 
GO


